name: Run Python Tests

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Ваше ФИО"
      GROUP_NUMBER: "Номер вашей группы"

    steps:
      # Шаг 1: Вывести ФИО, номер группы и ник на GitHub
      - name: Display user information
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group Number: ${{ env.GROUP_NUMBER }}"
          echo "GitHub Username: ${{ github.actor }}"

      # Шаг 2: Установить Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Шаг 3: Установить зависимости из requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Запустить юнит-тесты
      - name: Run unit tests
        run: |
          python -m pytest --doctest-modules
