name: Python application

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      FULL_NAME: "Гинкин Матвей Павлович"
      GROUP: "М3113"

    steps:
      - name: Display name and group 
      - run: |
          echo "Name: ${{ env.FULL_NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "GitHub username: ${{ github.actor }}"
          
      - name: Set up Python 3.13.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Test with pytest
        run: |
          python -m pytest tests/test.py
