name: Python Testing

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: Minapov Amir Lenarovich
      GROUP: M3113

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display author information
        run: |
          echo "Author: ${{ env.NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "GitHub username: ${{ github.repository_owner }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Check code style
        run: flake8
